/** The live idea's bird: a city pigeon seen from above, facing right, in the same -30..30 box as the other forms.
 *  Generated by scripts/art/pigeon.py (edit that, then regenerate this string): feathered wings and tail, iridescent neck, rump band, eyes and beak.
 *  Colors come from CSS variables (--b-*) so hovering or holding recolors it, and the wings are their own groups (.wing) so they can beat and fold
 *  without squashing the body. Gradient ids carry `uid` (the idea's id) so each bird has its own and removing one never breaks another. */
export const pigeon = (uid: string): string => `<svg viewBox="-30 -30 60 60" aria-hidden="true">
  <defs>
  <linearGradient id="bg-body-${uid}" x1="0" y1="-6" x2="0" y2="6" gradientUnits="userSpaceOnUse"><stop offset="0" class="s-hi"/><stop offset=".5" class="s-mid"/><stop offset="1" class="s-lo"/></linearGradient>
  <linearGradient id="bg-neck-${uid}" x1="0" y1="-5" x2="0" y2="5" gradientUnits="userSpaceOnUse"><stop offset="0" class="s-sheen1"/><stop offset=".5" class="s-sheen2"/><stop offset="1" class="s-sheen1"/></linearGradient>
  <linearGradient id="bg-tail-${uid}" x1="-12" y1="0" x2="-31" y2="0" gradientUnits="userSpaceOnUse"><stop offset="0" class="s-lo"/><stop offset=".6" class="s-lo"/><stop offset=".66" class="s-dark"/><stop offset="1" class="s-dark"/></linearGradient>
  <radialGradient id="bg-head-${uid}" cx=".4" cy=".35" r=".8"><stop offset="0" class="s-hi"/><stop offset="1" class="s-lo"/></radialGradient>
  </defs>
  <path class="bf bf-tail" fill="url(#bg-tail-${uid})" d="M-11.5 -4.3 L-22.8 -7.9 Q-28.8 -9.6 -28.1 -7.8 Q-23.8 -4.6 -12.5 -1.1 Z"></path>
  <path class="bf bf-tail" fill="url(#bg-tail-${uid})" d="M-11.6 -3.5 L-23.5 -6.2 Q-29.7 -7.4 -28.9 -5.7 Q-24.2 -2.8 -12.4 -0.1 Z"></path>
  <path class="bf bf-tail" fill="url(#bg-tail-${uid})" d="M-11.8 -2.6 L-24.2 -4 Q-30.7 -4.6 -29.7 -3 Q-24.6 -0.7 -12.2 0.8 Z"></path>
  <path class="bf bf-tail" fill="url(#bg-tail-${uid})" d="M-12 -1.7 L-24.9 -1.7 Q-31.7 -1.5 -30.5 0 Q-24.9 1.7 -12 1.7 Z"></path>
  <path class="bf bf-tail" fill="url(#bg-tail-${uid})" d="M-12.2 -0.8 L-24.6 0.7 Q-31.1 1.6 -29.7 3 Q-24.2 4 -11.8 2.6 Z"></path>
  <path class="bf bf-tail" fill="url(#bg-tail-${uid})" d="M-12.4 0.1 L-24.2 2.8 Q-30.4 4.4 -28.9 5.7 Q-23.5 6.2 -11.6 3.5 Z"></path>
  <path class="bf bf-tail" fill="url(#bg-tail-${uid})" d="M-12.5 1.1 L-23.8 4.6 Q-29.7 6.7 -28.1 7.8 Q-22.8 7.9 -11.5 4.3 Z"></path>
  <g class="wing wing-down">
  <path class="bf bf-prim" d="M3.6 -16.5 L-13.9 -20.4 Q-22.7 -22 -22 -19.5 Q-15.1 -15.3 2.4 -11.5 Z"></path>
  <path class="bf bf-prim" d="M2.9 -17.7 L-12.9 -23.5 Q-20.8 -26.1 -20.5 -23.5 Q-14.6 -18.6 1.1 -12.8 Z"></path>
  <path class="bf bf-prim" d="M2.2 -18.8 L-11.1 -25.8 Q-18 -29.1 -18 -26.5 Q-13.5 -21.2 -0.2 -14.2 Z"></path>
  <path class="bf bf-prim" d="M1.5 -19.8 L-8.6 -27.4 Q-14.1 -31.1 -14.5 -28.5 Q-11.7 -23.2 -1.5 -15.7 Z"></path>
  <path class="bf bf-prim" d="M0.9 -20.8 L-6.1 -28.1 Q-10.1 -32 -11 -29.5 Q-9.9 -24.6 -2.9 -17.2 Z"></path>
  <path class="bf bf-sec" d="M7.9 -8.2 L-7.5 -7.8 Q-15.3 -7.4 -14 -4.5 Q-7.3 -1.5 8.1 -1.8 Z"></path>
  <path class="bf bf-sec" d="M7.1 -9.8 L-8.8 -10.1 Q-16.7 -9.9 -15.6 -7 Q-8.9 -3.7 6.9 -3.4 Z"></path>
  <path class="bf bf-sec" d="M6.2 -11.4 L-10.1 -12.3 Q-18.2 -12.4 -17.2 -9.5 Q-10.4 -5.9 5.8 -5 Z"></path>
  <path class="bf bf-sec" d="M5.3 -13 L-11.4 -14.5 Q-19.7 -15 -18.8 -12 Q-12 -8.2 4.7 -6.6 Z"></path>
  <path class="bf bf-sec" d="M4.4 -14.6 L-12.7 -16.7 Q-21.2 -17.5 -20.4 -14.5 Q-13.5 -10.4 3.6 -8.2 Z"></path>
  <path class="bf bf-sec" d="M3.5 -16.2 L-14 -19 Q-22.7 -20 -22 -17 Q-15 -12.6 2.5 -9.8 Z"></path>
  <path class="bf bf-cov2" d="M-1.9 -22.8 L-6.8 -22.1 Q-10 -21.3 -8.5 -19 Q-6 -16.5 -1.1 -17.2 Z"></path>
  <path class="bf bf-cov2" d="M0.3 -19.7 L-4.9 -19.6 Q-8.4 -19.2 -7.1 -16.7 Q-4.8 -14 0.5 -14.1 Z"></path>
  <path class="bf bf-cov2" d="M2.5 -16.6 L-3.1 -17 Q-6.7 -17 -5.7 -14.4 Q-3.5 -11.4 2.1 -11 Z"></path>
  <path class="bf bf-cov2" d="M4.7 -13.5 L-1.3 -14.4 Q-5.1 -14.8 -4.3 -12.1 Q-2.2 -8.9 3.7 -7.9 Z"></path>
  <path class="bf bf-cov2" d="M6.8 -10.3 L0.5 -11.9 Q-3.5 -12.5 -2.9 -9.8 Q-0.9 -6.4 5.4 -4.9 Z"></path>
  <path class="bf bf-cov2" d="M8.8 -7.2 L2.2 -9.3 Q-1.9 -10.3 -1.5 -7.5 Q0.5 -3.9 7.2 -1.8 Z"></path>
  <path class="bf bf-cov" d="M-0.7 -21.9 L-4.2 -20.8 Q-6.8 -19.8 -5 -18 Q-2.8 -16.1 0.7 -17.1 Z"></path>
  <path class="bf bf-cov" d="M1.8 -18.2 L-2 -17.7 Q-4.8 -17.1 -3.4 -15 Q-1.4 -12.7 2.4 -13.2 Z"></path>
  <path class="bf bf-cov" d="M4.3 -14.3 L0.1 -14.5 Q-2.9 -14.3 -1.8 -12 Q-0 -9.5 4.2 -9.4 Z"></path>
  <path class="bf bf-cov" d="M6.7 -10.5 L2.2 -11.2 Q-1 -11.4 -0.1 -9 Q1.5 -6.2 6 -5.6 Z"></path>
  <path class="bf bf-cov" d="M9.1 -6.6 L4.2 -7.9 Q0.9 -8.5 1.5 -6 Q3 -3 7.9 -1.8 Z"></path>
  <path class="bf-bar" d="M-7.5 -14.7 L-1.2 -4.8"></path>
  <path class="bf-bar" d="M-14.5 -15.8 L-7.4 -4.7"></path>
  <path class="bf-edge" d="M9.4 -3.6 C8.4 -9.5 4.5 -16.5 -2.5 -22.5"></path>
  </g>
  <g class="wing wing-up">
  <path class="bf bf-prim" d="M2.4 11.5 L-15.1 15.3 Q-23.7 17.5 -22 19.5 Q-13.9 20.4 3.6 16.5 Z"></path>
  <path class="bf bf-prim" d="M1.1 12.8 L-14.6 18.6 Q-22.4 21.7 -20.5 23.5 Q-12.9 23.5 2.9 17.7 Z"></path>
  <path class="bf bf-prim" d="M-0.2 14.2 L-13.5 21.2 Q-20.2 25 -18 26.5 Q-11.1 25.8 2.2 18.8 Z"></path>
  <path class="bf bf-prim" d="M-1.5 15.7 L-11.7 23.2 Q-16.9 27.3 -14.5 28.5 Q-8.6 27.4 1.5 19.8 Z"></path>
  <path class="bf bf-prim" d="M-2.9 17.2 L-9.9 24.6 Q-13.5 28.8 -11 29.5 Q-6.1 28.1 0.9 20.8 Z"></path>
  <path class="bf bf-sec" d="M8.1 1.8 L-7.3 1.5 Q-15.1 1.6 -14 4.5 Q-7.5 7.8 7.9 8.2 Z"></path>
  <path class="bf bf-sec" d="M6.9 3.4 L-8.9 3.7 Q-16.9 4.1 -15.6 7 Q-8.8 10.1 7.1 9.8 Z"></path>
  <path class="bf bf-sec" d="M5.8 5 L-10.4 5.9 Q-18.6 6.7 -17.2 9.5 Q-10.1 12.3 6.2 11.4 Z"></path>
  <path class="bf bf-sec" d="M4.7 6.6 L-12 8.2 Q-20.3 9.2 -18.8 12 Q-11.4 14.5 5.3 13 Z"></path>
  <path class="bf bf-sec" d="M3.6 8.2 L-13.5 10.4 Q-22 11.8 -20.4 14.5 Q-12.7 16.7 4.4 14.6 Z"></path>
  <path class="bf bf-sec" d="M2.5 9.8 L-15 12.6 Q-23.6 14.3 -22 17 Q-14 19 3.5 16.2 Z"></path>
  <path class="bf bf-cov2" d="M-1.1 17.2 L-6 16.5 Q-9.3 16.3 -8.5 19 Q-6.8 22.1 -1.9 22.8 Z"></path>
  <path class="bf bf-cov2" d="M0.5 14.1 L-4.8 14 Q-8.2 14.1 -7.1 16.7 Q-4.9 19.6 0.3 19.7 Z"></path>
  <path class="bf bf-cov2" d="M2.1 11 L-3.5 11.4 Q-7.1 12 -5.7 14.4 Q-3.1 17 2.5 16.6 Z"></path>
  <path class="bf bf-cov2" d="M3.7 7.9 L-2.2 8.9 Q-5.9 9.8 -4.3 12.1 Q-1.3 14.4 4.7 13.5 Z"></path>
  <path class="bf bf-cov2" d="M5.4 4.9 L-0.9 6.4 Q-4.7 7.6 -2.9 9.8 Q0.5 11.9 6.8 10.3 Z"></path>
  <path class="bf bf-cov2" d="M7.2 1.8 L0.5 3.9 Q-3.4 5.5 -1.5 7.5 Q2.2 9.3 8.8 7.2 Z"></path>
  <path class="bf bf-cov" d="M0.7 17.1 L-2.8 16.1 Q-5.5 15.5 -5 18 Q-4.2 20.8 -0.7 21.9 Z"></path>
  <path class="bf bf-cov" d="M2.4 13.2 L-1.4 12.7 Q-4.3 12.6 -3.4 15 Q-2 17.7 1.8 18.2 Z"></path>
  <path class="bf bf-cov" d="M4.2 9.4 L-0 9.5 Q-3 9.8 -1.8 12 Q0.1 14.5 4.3 14.3 Z"></path>
  <path class="bf bf-cov" d="M6 5.6 L1.5 6.2 Q-1.6 7 -0.1 9 Q2.2 11.2 6.7 10.5 Z"></path>
  <path class="bf bf-cov" d="M7.9 1.8 L3 3 Q-0.2 4.1 1.5 6 Q4.2 7.9 9.1 6.6 Z"></path>
  <path class="bf-bar" d="M-7.5 14.7 L-1.2 4.8"></path>
  <path class="bf-bar" d="M-14.5 15.8 L-7.4 4.7"></path>
  <path class="bf-edge" d="M9.4 3.6 C8.4 9.5 4.5 16.5 -2.5 22.5"></path>
  </g>
  <path class="bird-body" d="M15 0 C14.5 -4.2 8 -6.3 -1 -6 C-9 -5.8 -14 -3.6 -15 0 C-14 3.6 -9 5.8 -1 6 C8 6.3 14.5 4.2 15 0 Z" fill="url(#bg-body-${uid})"></path>
  <ellipse class="bird-rump" cx="-12.2" cy="0" rx="2.2" ry="4.3"></ellipse>
  <path class="bird-spine" d="M13 0 L-13 0"></path>
  <path class="bird-neck" d="M17.5 -4.2 C14.5 -5.8 11 -5 9.6 -2.5 C8.8 0 8.8 0 9.6 2.5 C11 5 14.5 5.8 17.5 4.2 Z" fill="url(#bg-neck-${uid})"></path>
  <ellipse class="bird-head" cx="19.2" cy="0" rx="4.1" ry="3.7" fill="url(#bg-head-${uid})"></ellipse>
  <path class="bird-beak" d="M22.8 -1.1 L27.6 -0.35 Q28.4 0 27.6 0.35 L22.8 1.1 Z"></path>
  <ellipse class="bird-cere" cx="23.2" cy="0" rx=".95" ry="1"></ellipse>
  <circle class="bird-eye" cx="20.7" cy="-2.9" r=".95"></circle>
  <circle class="bird-eye" cx="20.7" cy="2.9" r=".95"></circle>
  <circle class="bird-pupil" cx="20.95" cy="-2.9" r=".42"></circle>
  <circle class="bird-pupil" cx="20.95" cy="2.9" r=".42"></circle></svg>`;
