"""Generates src/components/Skyline.astro: a line drawing of the New York skyline.

Each building is a closed outline filled with the sky's bottom color, drawn back to front, so nearer
buildings hide the lines of the ones behind them. A fixed seed keeps the drawing identical between runs.
Run: python3 scripts/skyline.py
"""
import random

W, H, BASE = 2400, 330, 328
rng = random.Random(11)

def box(x, w, h, cap=None):
    """A plain tower, optionally with a small rooftop box (cap = (width, height))."""
    pts = [(x, BASE), (x, BASE - h)]
    if cap:
        cw, ch = cap; cx = x + (w - cw) / 2
        pts += [(cx, BASE - h), (cx, BASE - h - ch), (cx + cw, BASE - h - ch), (cx + cw, BASE - h)]
    pts += [(x + w, BASE - h), (x + w, BASE)]
    return pts

def stepped(x, tiers):
    """Setback tower: tiers are (width, top height) from the street up, each centered on the first."""
    cx = x + tiers[0][0] / 2
    left, right, prev_h = [(x, BASE)], [(x + tiers[0][0], BASE)], 0
    for i, (w, h) in enumerate(tiers):
        if i: left.append((cx - w / 2, BASE - prev_h)); right.append((cx + w / 2, BASE - prev_h))
        left.append((cx - w / 2, BASE - h)); right.append((cx + w / 2, BASE - h))
        prev_h = h
    return left + right[::-1]

def empire_state(x):
    pts = stepped(x, [(96, 120), (74, 175), (52, 222), (30, 236), (14, 262)])
    i = len(pts) // 2
    return pts[:i] + [(x + 48, BASE - 300)] + pts[i:]  # the spire

def chrysler(x):
    w, cx = 54, x + 27
    pts = [(x, BASE), (x, BASE - 190)]
    for k, (half, h) in enumerate([(27, 190), (22, 206), (17, 220), (12, 233), (7, 244)]):  # the stacked crown
        pts += [(cx - half, BASE - h), (cx - half + 2, BASE - h - 8)] if k else []
    pts += [(cx - 3, BASE - 250), (cx, BASE - 290), (cx + 3, BASE - 250)]
    for half, h in [(7, 244), (12, 233), (17, 220), (22, 206)]:
        pts += [(cx + half - 2, BASE - h - 8), (cx + half, BASE - h)]
    pts += [(x + w, BASE - 190), (x + w, BASE)]
    return pts

def one_world_trade(x):
    return [(x, BASE), (x, BASE - 46), (x + 14, BASE - 268), (x + 34, BASE - 268), (x + 35, BASE - 326),
            (x + 37, BASE - 268), (x + 58, BASE - 268), (x + 72, BASE - 46), (x + 72, BASE)]

def slender(x, w, h):
    return box(x, w, h)

def generic_row(x0, x1, hmin, hmax):
    out, x = [], x0
    while x < x1:
        w = rng.randint(34, 86); h = rng.randint(hmin, hmax)
        cap = (rng.randint(10, 22), rng.randint(6, 16)) if rng.random() < .35 else None
        out.append(box(x, w, h, cap)); x += w + rng.randint(-10, 6)
    return out

back = generic_row(-20, W + 20, 70, 150)
front = generic_row(-10, 640, 30, 110) + generic_row(900, 1080, 40, 120) + generic_row(1720, W + 10, 30, 115)
landmarks = [one_world_trade(820), slender(1010, 30, 150), empire_state(1150), box(1290, 70, 140, (24, 14)),
             chrysler(1420), box(1500, 60, 120), slender(1600, 26, 246), box(1650, 66, 108)]

def d(pts):
    return "M" + " L".join(f"{round(a, 1)} {round(b, 1)}" for a, b in pts) + " Z"

paths = [f'<path class="far" d="{d(p)}"/>' for p in back] + [f'<path d="{d(p)}"/>' for p in front + landmarks]
svg = (f'<svg class="skyline" viewBox="0 0 {W} {H}" preserveAspectRatio="xMidYMax slice" aria-hidden="true">'
       + "".join(paths) + '</svg>')
open("src/components/Skyline.astro", "w").write(
    "---\n/* New York skyline, line drawing. Generated by scripts/skyline.py; edit that, not this. */\n---\n" + svg + "\n")
print(len(back), "far,", len(front) + len(landmarks), "near")
